include ~/.config/kitty/kitty-themes/themes/Dracula.conf
enable_audio_bell no

font_family      Hack Nerd Font
bold_font        Hack Nerd Font Bold
italic_font      Hack Nerd Font Italic
bold_italic_font Hack Nerd Font Bold Italic
font_size 10

