shell /home/linuxbrew/.linuxbrew/bin/tmux

include ~/.config/kitty/kitty-themes/themes/Dracula.conf
enable_audio_bell no

font_family      Hack Nerd Font
bold_font        Hack Nerd Font Bold
italic_font      Hack Nerd Font Italic
bold_italic_font Hack Nerd Font Bold Italic
font_size 10

# Make Ctrl+Backspace delete the previous word like Alt+Backspace/Ctrl+W.
map ctrl+backspace send_text all \x17


# selection:
# for chars: drag with mouse
# for words: double-click
# for lines: triple-click
# for block selection: Alt+drag
