context.modules = [
{   name = libpipewire-module-filter-chain
    args = {
        node.description = "Noise Canceling Source"
        media.name       = "Noise Canceling Source"
        filter.graph = {
            nodes = [
                {
                    type   = ladspa
                    name   = rnnoise
                    plugin = /usr/lib/ladspa/librnnoise_ladspa.so
                    label  = noise_suppressor_mono
                    control = {
                        "VAD Threshold (%)" 30.0
                    }
                }
            ]
        }
        capture.props = {
            node.name      = "capture.rnnoise_source"
            node.passive   = true
            audio.rate     = 48000
            # Forces the filter to take only the mono signal from your mic
            audio.channels = 1
            audio.position = [ MONO ]
        }
        playback.props = {
            node.name          = "rnnoise_source"
            media.class        = Audio/Source
            audio.rate         = 48000
            audio.channels     = 1
            audio.position     = [ MONO ]
            node.force-quantum = 1024
        }
    }
}
]
